root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/bin/main.exe ."
bin = "./tmp/bin/main.exe"
delay = 1000
exclude_dir = ["assets", "tmp"]
exclude_regex = [".*_templ.go"]
kill_delay = "5s"
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "css"]
send_interrupt = false
stop_on_error = false

[color]
app = "white"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = true

[proxy]
enabled = true
proxy_port = 7331
app_port = 8090



